server:
  port: 8220

spring:
  application:
    name: inventory-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  instance:
      status-page-url: http://localhost:${server.port}/swagger-ui.html #配置swagger-ui方便在注册中心可以跳转到提供者的接口信息文档

#安全配置
security:
  oauth2:
    resource:
      id: inventory-server
      #指定用户信息地址
      user-info-uri: http://localhost:8120/api/auth/user
      prefer-token-info: false

logging:
  config: classpath:logback-spring.xml
  path: C:/xlfd-cloud/xlfd-cloud-inventory